<?php

$alumnos = array();
$alumnos[] = array('nombre' => 'Alberto', 'apellido1' => 'Polanco', 'apellido2' => 'Sánchez', 'cuenta' => 'albe');
$alumnos[] = array('nombre' => 'Alvaro', 'apellido1' => 'Jiménez', 'apellido2' => 'Lopez', 'cuenta' => 'alva');
$alumnos[] = array('nombre' => 'Aranzazu', 'apellido1' => 'Pérez', 'apellido2' => 'Laborda', 'cuenta' => 'aran');
$alumnos[] = array('nombre' => 'Aritz', 'apellido1' => 'Hernáez', 'apellido2' => 'García', 'cuenta' => 'arit');
$alumnos[] = array('nombre' => 'Asier', 'apellido1' => 'Pérez', 'apellido2' => 'Tamayo', 'cuenta' => 'asie');
$alumnos[] = array('nombre' => 'Eder', 'apellido1' => 'Moledo', 'apellido2' => 'Villalba', 'cuenta' => 'eder');
$alumnos[] = array('nombre' => 'Eneko', 'apellido1' => 'de la Torre', 'apellido2' => 'Sánchez', 'cuenta' => 'enek');
$alumnos[] = array('nombre' => 'Francisco Borja', 'apellido1' => 'Navarro', 'apellido2' => 'Río', 'cuenta' => 'fran');
$alumnos[] = array('nombre' => 'Gaizka', 'apellido1' => 'Lorenzo', 'apellido2' => 'Jiménez', 'cuenta' => 'gaiz');
$alumnos[] = array('nombre' => 'Iñaki', 'apellido1' => 'Angulo', 'apellido2' => 'Tarancón', 'cuenta' => 'inak');
$alumnos[] = array('nombre' => 'Iñaki', 'apellido1' => 'Demón', 'apellido2' => 'Fernandez', 'cuenta' => 'inai');
$alumnos[] = array('nombre' => 'Iñigo', 'apellido1' => 'Casado', 'apellido2' => 'Rico', 'cuenta' => 'inig');
$alumnos[] = array('nombre' => 'Iratxe', 'apellido1' => 'Urriolabeitia', 'apellido2' => 'Zabala', 'cuenta' => 'irat');
$alumnos[] = array('nombre' => 'Isaac Jacob', 'apellido1' => 'Pazos', 'apellido2' => 'López', 'cuenta' => 'isaa');
$alumnos[] = array('nombre' => 'Jon', 'apellido1' => 'Aróstegui', 'apellido2' => 'Brizuela', 'cuenta' => 'jona');
$alumnos[] = array('nombre' => 'Jon', 'apellido1' => 'Elorriaga', 'apellido2' => 'Bilbao', 'cuenta' => 'jone');
$alumnos[] = array('nombre' => 'Lander', 'apellido1' => 'Eguskiza', 'apellido2' => 'Lamelas', 'cuenta' => 'land');
$alumnos[] = array('nombre' => 'Luis Fernando', 'apellido1' => 'Coca', 'apellido2' => 'Cabrera', 'cuenta' => 'luis');
$alumnos[] = array('nombre' => 'Miguel', 'apellido1' => 'Rodrigo', 'apellido2' => 'Ortega', 'cuenta' => 'migu');
$alumnos[] = array('nombre' => 'Sergio', 'apellido1' => 'Castro', 'apellido2' => 'Bravo', 'cuenta' => 'serg');
$alumnos[] = array('nombre' => 'Xabier', 'apellido1' => 'Isla', 'apellido2' => 'Rodriguez', 'cuenta' => 'xabi');

$asignaturas = array();
$asignaturas['IS'] = "Ingeniería del software";
$asignaturas['AC'] = "Arquitectura de computadores";
$asignaturas['MP'] = "Metodología de programación";
$asignaturas['EDA'] = "Estructuras de datos";
$asignaturas['NET'] = "Redes y comunicaciones";
$asignaturas['BD'] = "Bases de datos";
$asignaturas['LF'] = "Lógica formal";
$asignaturas['IA'] = "Inteligencia artificial";

$calificaciones = array();
$calificaciones[] = array("cuenta" => "luis", "asignatura" => "EDA", "convocatoria" => 1, "calificacion" => 4.4);
$calificaciones[] = array("cuenta" => "luis", "asignatura" => "EDA", "convocatoria" => 2, "calificacion" => 4.4);
$calificaciones[] = array("cuenta" => "luis", "asignatura" => "EDA", "convocatoria" => 3, "calificacion" => 7);
$calificaciones[] = array("cuenta" => "luis", "asignatura" => "NET", "convocatoria" => 1, "calificacion" => 5.9);
$calificaciones[] = array("cuenta" => "luis", "asignatura" => "BD", "convocatoria" => 1, "calificacion" => 3.7);
$calificaciones[] = array("cuenta" => "xabi", "asignatura" => "NET", "convocatoria" => 1, "calificacion" => 6.3);
$calificaciones[] = array("cuenta" => "xabi", "asignatura" => "BD", "convocatoria" => 1, "calificacion" => 4.9);
$calificaciones[] = array("cuenta" => "xabi", "asignatura" => "BD", "convocatoria" => 2, "calificacion" => 8.4);
$calificaciones[] = array("cuenta" => "serg", "asignatura" => "MP", "convocatoria" => 3, "calificacion" => 4.9);
$calificaciones[] = array("cuenta" => "serg", "asignatura" => "MP", "convocatoria" => 4, "calificacion" => 8.6);
$calificaciones[] = array("cuenta" => "serg", "asignatura" => "EDA", "convocatoria" => 1, "calificacion" => 0.3);
$calificaciones[] = array("cuenta" => "serg", "asignatura" => "EDA", "convocatoria" => 2, "calificacion" => 9.2);
$calificaciones[] = array("cuenta" => "serg", "asignatura" => "NET", "convocatoria" => 1, "calificacion" => 0.7);
$calificaciones[] = array("cuenta" => "serg", "asignatura" => "NET", "convocatoria" => 2, "calificacion" => 2.2);
$calificaciones[] = array("cuenta" => "luis", "asignatura" => "BD", "convocatoria" => 2, "calificacion" => 9.3);
$calificaciones[] = array("cuenta" => "luis", "asignatura" => "LF", "convocatoria" => 1, "calificacion" => 10);
$calificaciones[] = array("cuenta" => "luis", "asignatura" => "IA", "convocatoria" => 1, "calificacion" => 3.8);
$calificaciones[] = array("cuenta" => "luis", "asignatura" => "IA", "convocatoria" => 2, "calificacion" => 6);
$calificaciones[] = array("cuenta" => "migu", "asignatura" => "IS", "convocatoria" => 1, "calificacion" => 6.6);
$calificaciones[] = array("cuenta" => "migu", "asignatura" => "AC", "convocatoria" => 1, "calificacion" => 5.5);
$calificaciones[] = array("cuenta" => "migu", "asignatura" => "MP", "convocatoria" => 1, "calificacion" => 2.1);
$calificaciones[] = array("cuenta" => "xabi", "asignatura" => "EDA", "convocatoria" => 1, "calificacion" => 4.8);
$calificaciones[] = array("cuenta" => "xabi", "asignatura" => "EDA", "convocatoria" => 2, "calificacion" => 5.8);
$calificaciones[] = array("cuenta" => "serg", "asignatura" => "NET", "convocatoria" => 3, "calificacion" => 1.6);
$calificaciones[] = array("cuenta" => "serg", "asignatura" => "NET", "convocatoria" => 4, "calificacion" => 1.4);
$calificaciones[] = array("cuenta" => "serg", "asignatura" => "NET", "convocatoria" => 5, "calificacion" => 3.6);
$calificaciones[] = array("cuenta" => "serg", "asignatura" => "NET", "convocatoria" => 6, "calificacion" => 3.5);
$calificaciones[] = array("cuenta" => "serg", "asignatura" => "BD", "convocatoria" => 1, "calificacion" => 3.6);
$calificaciones[] = array("cuenta" => "serg", "asignatura" => "BD", "convocatoria" => 2, "calificacion" => 9.8);
$calificaciones[] = array("cuenta" => "serg", "asignatura" => "LF", "convocatoria" => 1, "calificacion" => 4.3);
$calificaciones[] = array("cuenta" => "migu", "asignatura" => "MP", "convocatoria" => 2, "calificacion" => 6.4);
$calificaciones[] = array("cuenta" => "migu", "asignatura" => "EDA", "convocatoria" => 1, "calificacion" => 2.5);
$calificaciones[] = array("cuenta" => "migu", "asignatura" => "EDA", "convocatoria" => 2, "calificacion" => 7.5);
$calificaciones[] = array("cuenta" => "migu", "asignatura" => "NET", "convocatoria" => 1, "calificacion" => 4);
$calificaciones[] = array("cuenta" => "migu", "asignatura" => "NET", "convocatoria" => 2, "calificacion" => 2);
$calificaciones[] = array("cuenta" => "migu", "asignatura" => "NET", "convocatoria" => 3, "calificacion" => 6.9);
$calificaciones[] = array("cuenta" => "migu", "asignatura" => "BD", "convocatoria" => 1, "calificacion" => 4.1);
$calificaciones[] = array("cuenta" => "migu", "asignatura" => "BD", "convocatoria" => 2, "calificacion" => 0.7);
$calificaciones[] = array("cuenta" => "migu", "asignatura" => "BD", "convocatoria" => 3, "calificacion" => 7.8);
$calificaciones[] = array("cuenta" => "migu", "asignatura" => "LF", "convocatoria" => 1, "calificacion" => 4.6);
$calificaciones[] = array("cuenta" => "migu", "asignatura" => "LF", "convocatoria" => 2, "calificacion" => 7.1);
$calificaciones[] = array("cuenta" => "migu", "asignatura" => "IA", "convocatoria" => 1, "calificacion" => 2.9);
$calificaciones[] = array("cuenta" => "migu", "asignatura" => "IA", "convocatoria" => 2, "calificacion" => 5.8);
$calificaciones[] = array("cuenta" => "serg", "asignatura" => "IS", "convocatoria" => 1, "calificacion" => 0.1);
$calificaciones[] = array("cuenta" => "serg", "asignatura" => "IS", "convocatoria" => 2, "calificacion" => 3.3);
$calificaciones[] = array("cuenta" => "serg", "asignatura" => "IS", "convocatoria" => 3, "calificacion" => 7.7);
$calificaciones[] = array("cuenta" => "xabi", "asignatura" => "AC", "convocatoria" => 2, "calificacion" => 3.3);
$calificaciones[] = array("cuenta" => "xabi", "asignatura" => "AC", "convocatoria" => 3, "calificacion" => 0.1);
$calificaciones[] = array("cuenta" => "xabi", "asignatura" => "LF", "convocatoria" => 1, "calificacion" => 3.7);
$calificaciones[] = array("cuenta" => "xabi", "asignatura" => "LF", "convocatoria" => 2, "calificacion" => 5.1);
$calificaciones[] = array("cuenta" => "xabi", "asignatura" => "IA", "convocatoria" => 1, "calificacion" => 7.9);
$calificaciones[] = array("cuenta" => "serg", "asignatura" => "AC", "convocatoria" => 1, "calificacion" => 6.4);
$calificaciones[] = array("cuenta" => "serg", "asignatura" => "MP", "convocatoria" => 1, "calificacion" => 4);
$calificaciones[] = array("cuenta" => "serg", "asignatura" => "MP", "convocatoria" => 2, "calificacion" => 1.7);
$calificaciones[] = array("cuenta" => "xabi", "asignatura" => "AC", "convocatoria" => 4, "calificacion" => 6.9);
$calificaciones[] = array("cuenta" => "xabi", "asignatura" => "MP", "convocatoria" => 1, "calificacion" => 5.3);
$calificaciones[] = array("cuenta" => "serg", "asignatura" => "LF", "convocatoria" => 2, "calificacion" => 5.1);
$calificaciones[] = array("cuenta" => "serg", "asignatura" => "IA", "convocatoria" => 1, "calificacion" => 8.2);
$calificaciones[] = array("cuenta" => "xabi", "asignatura" => "IS", "convocatoria" => 1, "calificacion" => 1.2);
$calificaciones[] = array("cuenta" => "xabi", "asignatura" => "IS", "convocatoria" => 2, "calificacion" => 5.7);
$calificaciones[] = array("cuenta" => "xabi", "asignatura" => "AC", "convocatoria" => 1, "calificacion" => 4);

?>